# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Flink AI Flow CI Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_and_itest:

    runs-on: ubuntu-latest
    env:
      FLINK_HOME: /tmp/flink-1.13.1
      AIRFLOW_HOME: ~/airflow
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Start MySQL Server
      run: "docker run --name=mysql8 \
            -e MYSQL_ROOT_PASSWORD=password \
            -e MYSQL_USER=airflow \
            -e MYSQL_PASSWORD=airflow \
            -e MYSQL_DATABASE=airflow \
            --health-cmd='mysqladmin ping' \
            -v /$(pwd)/flink-ai-flow/scripts/mysql/conf.d:/etc/mysql/conf.d \
            -v /tmp:/tmp \
            -v /$(pwd)/flink-ai-flow/scripts/mysql:/var/log/syslog \
            --cap-add=sys_nice \
            -d \
            -p 3306:3306 \
            mysql:8.0 \
            --port=3306"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        pip install ./flink-ai-flow/lib/notification_service
        pip install ./flink-ai-flow/lib/airflow
        pip install ./flink-ai-flow
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax erroservice.pys or undefined names
        flake8 flink-ai-flow --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 flink-ai-flow --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: prepare e2e test environment
      run: |
        /bin/bash flink-ai-flow/scripts/ci_prepare.sh 3306 airflow airflow
    - name: run ci test
      run: |
        /bin/bash flink-ai-flow/run_tests.sh
    - name: read log
      if: ${{ always() }}
      run: |
        echo "--------------------"
        sudo cat /tmp/mysql_error.log || true
        echo "--------------------"
        sudo cat /tmp/mysql_general.log || true
        echo "--------------------"
        cat /var/log/syslog || true
        echo "--------------------"
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "show databases;"
        mysql --host 127.0.0.1 --port 3306 -uroot -ppassword -e "SHOW GLOBAL STATUS LIKE  'Aborted_connects';"
